### ISSUE TITLE
Board availability

### ISSUE THREAD

**Issue by SloMusti** [madcowswe/Servo#1]
A very impressive project and thus opening an issue of that would be nice have boards available from somewhere.

I am building http://goodenoughcnc.eu open hardware low-cost CNC machines and your project would be an awesome fit, giving much better performance. Let me know what would be the best way to buy a few boards from you and support the project.

**Comment by UAVEEGDRONE** [comment]
How much for the boards....????

**Comment by madcowswe** [comment]
I am currently fixing the last set of hardware design bugs. When I am ready, I will make a small batch, and make boards available to developers. As the hardware stabilizes, I will facilitate larger batches after that.

**Comment by SloMusti** [comment]
Awesome, please let me know when available, happy to cover the cost and help with prototype batch.

**Comment by madcowswe** [comment]
Boards are now available [here](https://hackaday.io/project/11583-odrive-high-performance-motor-control/log/40702-boards-and-development).
